repos:
  - repo: local
    hooks:
      - id: update-ha-cards-links
        name: Update HA cards links in README
        entry: python .dev-scripts/update_ha_cards_links.py
        language: python
        pass_filenames: false
        files: ^(ha_card/.*\.yaml|README\.md)$
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7 # Use the same version as installed
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5 # Use the latest version
    hooks:
      - id: codespell
        args: ["--write-changes"] # Enable auto-fix
