# Default duration of events after start time in hours (e.g., 0.5, 2.75, 4)
# If another event is due to start after the current event within the dafult
# duration, the current event will be shortened to make room for the next event.
event_duration: 4  # Duration in hours