[project]
name = "twickenham-events"
version = "0.1.0"
description = "Fetch and process Twickenham Stadium events"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
readme = "README.md"

[tool.poetry]
packages = [
    { include = "core" },
    { include = "tests", format = "sdist" }
]
package-mode = true

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.0"
paho-mqtt = "^1.6.1"
pyyaml = "^6.0.1"

[tool.poetry.group.ai.dependencies]
google-generativeai = "^0.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
