[tool.poetry]
name = "twickenham-events"
version = "0.1.0"
package-mode = false
description = "A scraper for Twickenham Events"
authors = ["Ron Schaeffer"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = "^2.25.1" 
beautifulsoup4 = "^4.9.3"
poetry = "^2.0.0"
pyyaml = "^6.0.2"

[poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
