# Event settings
default_duration: 6  # Duration in hours

# Default duration of events after start time in hours (e.g., 0.5, 2.75, 4)
# If another event is due to start after the current event within the dafult
# duration, the current event will be shortened to make room for the next event.

# MQTT Configuration
mqtt:
  broker_url: 10.10.10.21
  broker_port: 8883
  client_id: server
  username: 136worple
  password: 011020MQTT
  topics:
    next: twick_events/next
    all_upcoming: twick_events/all_upcoming