# Event settings
default_duration: 6 # Duration in hours

# MQTT Configuration
mqtt:
  broker_url: 10.10.10.21
  broker_port: 8883
  client_id: server
  security: "username"

  # Authentication settings
  auth:
    username: 136worple
    password: 011020MQTT

  # TLS settings
  tls:
    ca_cert: null
    client_cert: null
    client_key: null
    verify: false

  topics:
    next: "twickenham_events/events/next"
    next_day_summary: "twickenham_events/events/next_day_summary"
    all_upcoming: "twickenham_events/events/all_upcoming"
    errors: "twickenham_events/events/errors"

# Home Assistant Integration
home_assistant:
  enabled: true
  discovery_prefix: "homeassistant" # Default Home Assistant discovery topic
