# Event source
scraping:
  url: "https://www.richmond.gov.uk/services/parking/cpz/twickenham_events"

# Rules for determining when an event is over
event_rules:
  end_of_day_cutoff: "23:00" # Time to consider all events for the day over
  next_event_delay_hours: 1 # Hours after an event starts before it's considered over (if another event follows)

# MQTT Configuration
mqtt:
  enabled: true
  broker_url: 10.10.10.21
  broker_port: 8883
  client_id: server
  security: "username"

  # Authentication settings
  auth:
    username: 136worple
    password: 011020MQTT

  # TLS settings
  tls:
    ca_cert: null
    client_cert: null
    client_key: null
    verify: false

  topics:
    next: "twickenham_events/events/next"
    next_day_summary: "twickenham_events/events/next_day_summary"
    all_upcoming: "twickenham_events/events/all_upcoming"
    status: "twickenham_events/status"

# Home Assistant Integration
home_assistant:
  enabled: true
  discovery_prefix: "homeassistant" # Default Home Assistant discovery topic

# Event Name Shortening (AI-powered)
event_shortener:
  enabled: true # Set to true and add API key to enable
  api_key: "AIzaSyBnS_jrez0HfAgd2aONJy1s0VAm79yvNy8" # Your Google Gemini API key
  model_name: "gemini-2.5-pro"
  char_limit: 16
  prompt_template: >
    You are an expert editor. Your task is to shorten event names
    to a maximum of {char_limit} characters while keeping them recognizable.
    The events are usually rugby matches, but can also be concerts.
    Use standard abbreviations.

    Examples:
    fixture: Women's Rugby World Cup Final
    fixture_short: W RWC Final

    fixture: Taylor Swift | The Eras Tour
    fixture_short: Taylor Swift

    fixture: Harlequins Big Game
    fixture_short: Quins Big Game
    ---
    Now, shorten this event name:
    fixture: {event_name}
    fixture_short:
