# Home Assistant MQTT Discovery Configuration for Twickenham Events
# This file defines how the Twickenham Events sensors appear in Home Assistant

# Device configuration - shared across all sensors
device:
  identifiers: ["twickenham_events"]
  name: "Twickenham Events"
  manufacturer: "Ron Schaeffer"
  model: "Event Scraper v1.0"
  sw_version: "0.1.0"

# Individual sensor configurations
sensors:
  # All upcoming events sensor
  all_upcoming:
    name: "All Upcoming"
    unique_id: "twickenham_events_all_upcoming"
    object_id: "twickenham_events_all_upcoming"
    state_topic: "twickenham_events/events/all_upcoming"
    json_attributes_topic: "twickenham_events/events/all_upcoming"
    value_template: "{{ value_json.events | count }}"
    json_attributes_template: "{{ value_json | tojson }}"
    icon: "mdi:calendar-multiple"
    unit_of_measurement: "events"

  # Next event sensor
  next:
    name: "Next Event"
    unique_id: "twickenham_events_next"
    object_id: "twickenham_events_next"
    state_topic: "twickenham_events/events/next"
    json_attributes_topic: "twickenham_events/events/next"
    value_template: "{{ value_json.event.fixture if value_json.event else 'None' }}"
    json_attributes_template: "{{ value_json | tojson }}"
    icon: "mdi:calendar-star"

# Binary sensors
binary_sensors:
  # Status sensor (error detection)
  status:
    name: "Status"
    unique_id: "twickenham_events_status"
    object_id: "twickenham_events_status"
    state_topic: "twickenham_events/status"
    json_attributes_topic: "twickenham_events/status"
    device_class: "problem"
    value_template: "{{ 'ON' if value_json.status == 'error' else 'OFF' }}"
    json_attributes_template: "{{ value_json | tojson }}"
    icon: "mdi:alert-circle"
