# config/ha_entities.yaml

# This block defines the parent device that will group all the sensors together
# in Home Assistant, providing a cleaner integration.
device:
  identifiers: ["twickenham_events_monitor"]
  name: "Twickenham Events Monitor"
  manufacturer: "ronschaeffer"
  model: "Event Monitor"
  sw_version: "0.1.0-f275ea2-dirty" # Dynamic version from Git

# This block defines the individual sensors that belong to the device above.
sensors:
  # Sensor for the very next upcoming event
  - name: "Next Twickenham Event"
    unique_id: "twick_next_event"
    state_topic: "twickenham_events/events/next"
    value_template: "{{ value_json.event.fixture }}"
    json_attributes_topic: "twickenham_events/events/next"
    json_attributes_template: "{{ value_json.event | tojson }}"
    icon: "mdi:calendar-clock"

  # Sensor for the summary of events on the next event day
  - name: "Next Twickenham Event Day Summary"
    unique_id: "twick_next_day_summary"
    state_topic: "twickenham_events/events/next_day_summary"
    value_template: >
      {{ value_json.summary.event_count }} event(s) on {{ value_json.summary.date }}
    json_attributes_topic: "twickenham_events/events/next_day_summary"
    json_attributes_template: "{{ value_json.summary | tojson }}"
    icon: "mdi:calendar-text"

  # Sensor for all upcoming events
  - name: "All Upcoming Twickenham Events"
    unique_id: "twick_all_upcoming_events"
    state_topic: "twickenham_events/events/all_upcoming"
    value_template: "{{ value_json.events | count }} upcoming events"
    json_attributes_topic: "twickenham_events/events/all_upcoming"
    json_attributes_template: "{{ value_json.events | tojson }}"
    icon: "mdi:calendar-multiple"

  # Sensor for application errors
  - name: "Twickenham Events Errors"
    unique_id: "twick_events_errors"
    state_topic: "twickenham_events/events/errors"
    value_template: "{{ value_json.error_count }} errors"
    json_attributes_topic: "twickenham_events/events/errors"
    json_attributes_template: "{{ value_json.errors | tojson }}"
    icon: "mdi:alert-circle-outline"
